---
language: node_js
node_js:
  - '10'

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/ # version tags
    - /^v\d+-(\d+|x)(-x)?/ # version branches

addons:
  chrome: stable
  firefox: latest-esr

cache:
  yarn: true

stages:
  - test
  - older version tests
  - deploy

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs tests with current locked deps and linting
    - stage: test
      name: 'test'
      script:
        - yarn lint
        - yarn test
    - name: 'floating dependencies'
      install: yarn install --no-lockfile --non-interactive --ignore-engines
      script: yarn test

    # runs tests against each supported Ember version
    - stage: older version tests
      env: EMBER_TRY_SCENARIO=ember-lts-3.8
    - env: EMBER_TRY_SCENARIO=ember-lts-3.12
    - env: EMBER_TRY_SCENARIO=ember-lts-3.16
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: EMBER_TRY_SCENARIO=ember-without-application-wrapper

    # runs deploy if running on a specific tag
    - stage: deploy
      if: tag IS present
      name: 'npm-publish'
      install: yarn global add auto-dist-tag@0.1
      script: auto-dist-tag --write
      deploy:
        provider: npm
        email: stefan.penner+ember-cli@gmail.com
        api_key:
          secure: rKej7q7tP+K3XUsKftqVhw8/Tgx6pn30OzV0g39RGVTRjWKvLu36UlF3LtP0AfofIKqsnPcvy+VaV9uCOOFiG6xBlXtVjxtqbplBmvKU1SjBHrwtlK61SdlXNKwIagWxBSbCUNxj+ka0d8gpIxS+sNw4sKGWHufH0CoAjpkerog=
        on:
          tags: true
          repo: emberjs/ember-test-helpers

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --ignore-engines

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
